## COPYRIGHT (C) HARRY CLARK 2025
## LIGHTWEIGHT, VERSATILE Z80 EMULATOR

## SET THE DEFAULT TARGET TO ALL (THIS IS FOR EASE OF USE WHEN COMPILING)

.DEFAULT_GOAL := all

## ENABLE A SIMPLE PARALLEL EXECUTION PRAGMATIC FOR FASTER EXECUTION TIMES

MAKEFLAGS += -j$(shell nproc)