// COPYRIGHT (C) HARRY CLARK 2025
// LIGHTWEIGHT, VERSATILE Z80 EMULATOR

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY ENCOMPASSING THE UTILITY
// OF THE CPU AND IT'S SUBSEQUENT LOGIC, FUNCTION AND NECESSITIES

// NESTED INCLUDES

#include "z80.h"
#include "z80OPCODE.h"

// INITIALISE THE CPU STRUCTURE BASED ON IT'S RESPECTIVE MEMBERS
// MUCH TO THE CONTEMPORAIRES OF LIB68K, THIS WILL FOLLOW A MUCH SIMPLER INITIALISATION SCHEMA BY COMP

// THIS IS LARGE IN PART DUE TO THE FACT THAT THE Z80 IS OBVIOUSLY A LESS COMPLICATED
// MICROPROCESSOR TO WORK WITH

void Z80_INIT(CPU_Z80* const Z80)
{
    Z80->PC = 0x0000;
    Z80->SP = 0xFFFF;
    Z80->IRQ_MODE = 0;
    Z80->HALT = 0;
    Z80->INT_PENDING = 0;
    Z80->NMI_PENDING = 0;
    Z80->Z80_MEM->MEMORY_BASE = NULL;
    Z80->Z80_MEM->READ_8 = NULL;
    Z80->Z80_MEM->READ_16 = NULL;
    Z80->Z80_MEM->WRITE_8 = NULL;
    Z80->Z80_MEM->WRITE_16 = NULL;
}
